### ISSUE TITLE
Doesn't seem to work on Safari

### ISSUE THREAD

**Issue by richpeniche** [rubentd/gifplayer#4]
I was doing cross-browsing testing of http://rubentd.com/gifplayer and it doesn't seem to work on Safari (MacOS Yosemite).

**Comment by miri-am** [comment]
It works on Safari. That it is not working on the preview page is caused by the following error:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery-1.10.2.min.map, line 0)
```
