### ISSUE TITLE
option for canvas title image

### ISSUE THREAD

**Issue by evilebottnawi** [rubentd/gifplayer#6]
What do you think?

**Comment by OPGamesTH** [comment]
Download Script : https://drive.google.com/file/d/0BzBdI6OVibQUYlJaaDJyVDFjWjA/view?usp=sharing

preview image : http://i.imgur.com/qU1Mkyl.png

exmaple with gif video
`<img class="gif" data-mode="video" data-mp4="url_mp4" src="url_image" data-title="My Title" data-url="url title" >`
