### ISSUE TITLE
Video Mode Errors

### ISSUE THREAD

**Issue by STF-GR** [rubentd/gifplayer#7]
On an Android version 4.1.2. , Firefox 37.0.2, Opera 29.0 it doesn't work right.
On Android and Firefox it makes duplicate videos underneath the original one.
On Opera when pause it doesn't show the play button and when played it shows the play button.

On Chrome its works OK!

**Comment by valentinmari** [comment]
Please mark as fixed

**Comment by rubentd** [comment]
Thanks a lot for your help
